### ISSUE TITLE
Console options declared with `--` prefix

### ISSUE THREAD

**Issue by gharlan** [psalm/psalm-plugin-symfony#105]
Usually options are declared without the `--` prefix:

```php
$this->addOption('boolean', null, InputOption::VALUE_NONE);
```

But symfony allows to add the prefix:

```php
$this->addOption('--boolean', null, InputOption::VALUE_NONE);
```

But this plugin does not resolve the type if the prefix is added.

**Comment by seferov** [comment]
Thank you for the report!
