### ISSUE TITLE
Psalm strategy with Voter::voteOnAttribute, NormalizerInterface::normalize, and similar methods.

### ISSUE THREAD

**Issue by VincentLanglet** [psalm/psalm-plugin-symfony#107]
From the Voter class
```
    /**
     * Perform a single access check operation on a given attribute, subject and token.
     * It is safe to assume that $attribute and $subject already passed the "supports()" method check.
     *
     * @param string $attribute
     * @param mixed  $subject
     *
     * @return bool
     */
    abstract protected function voteOnAttribute($attribute, $subject, TokenInterface $token);
```

Subject has a `mixed` type, but since there is a `supports` method, it's safe to restrict the `$subject` type.

With the following method `supports`
```
    public function supports($attribute, $subject)
    {
        if (self::CONTRACT_SHOW !== $attribute) {
            return false;
        }

        if (!$subject instanceof Contract) {
            return false;
        }

        return true;
    }
```
It should be ok to write
```
    /**
     * @param string         $attribute
     * @param Contract       $subject
     * @param TokenInterface $token
     *
     * @return bool
     */
    public function voteOnAttribute($attribute, $subject, TokenInterface $token)
```
Without getting a `MoreSpecificImplementedParamType` error.

Same for others classes with a `supports` method.

Is there a way to avoid the error ? Does a stub or something like this could be added to this plugin ? Or the only solution is to use `psalm-suppress` ?

**Comment by VincentLanglet** [comment]
Hi @seferov ! Any advice/idea about this situation ?
What would be the possible PR to make in this repository ?

**Comment by seferov** [comment]
@VincentLanglet thanks for reporting. I am not sure it is doable with stubs but I think it is possible handle with plugin hooks

**Comment by VincentLanglet** [comment]
I'm new to this @seferov, could you help me ?

I assume that the rule would be "If the class extends `Symfony\Component\Security\Core\Authorization\Voter\Voter`, it automatically add a `psalm-suppress MoreSpecificImplementedParamType` to the `voteOnAttribute`".

Then the same could be done if the class implements NormalizerInterface...

**Comment by seferov** [comment]
@VincentLanglet exactly. It would be hard to infer type of subject from `supports` method and assign type to the subject on voteOnAttribute. Just suppressing MoreSpecificImplementedParamType on voteOnAttribute is ok I think. To do so I added voter stub https://github.com/psalm/psalm-plugin-symfony/pull/127

**Comment by VincentLanglet** [comment]
> @VincentLanglet exactly. It would be hard to infer type of subject from `supports` method and assign type to the subject on voteOnAttribute. Just suppressing MoreSpecificImplementedParamType on voteOnAttribute is ok I think. 

I agree

> To do so I added voter stub #127

Oh didn't know a stub could have a psalm suppress.
Thanks for your PR, it gives me a great example of how to contribute.

There is also:
- `NormalizerInterface::normalize` (since there is a `supportsNormalization` method).
- `DenormalizerInterface::denormalize` (since there is a `supportsDenormalization` method).

But I'm not sure if I should do the contribution.
When I look at the Normalizer provided by Symfony they are checking again the data even if it's done in the `supportNormalization` method.
```
class JsonSerializableNormalizer extends AbstractNormalizer
{
    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = [])
    {
        if ($this->isCircularReference($object, $context)) {
            return $this->handleCircularReference($object);
        }

        if (!$object instanceof \JsonSerializable) {
            throw new InvalidArgumentException(sprintf('The object must implement "%s".', \JsonSerializable::class));
        }

        if (!$this->serializer instanceof NormalizerInterface) {
            throw new LogicException('Cannot normalize object because injected serializer is not a normalizer.');
        }

        return $this->serializer->normalize($object->jsonSerialize(), $format, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \JsonSerializable;
    }
```
Maybe it's because the method is public. (Voter::voteOnAttribute was protected instead)

So I think your PR may be enough to close the issue.

**Comment by TheCelavi** [comment]
@seferov Seams that there is an conflict between phpstan and psalm plugins for Symfony, phpstan defines generics.

![image](https://github.com/psalm/psalm-plugin-symfony/assets/410738/c4d45402-c2f5-4178-a585-fadde0b6ce1b)
