### ISSUE TITLE
Document the two twig tainting approaches

### ISSUE THREAD

**Issue by micheh** [psalm/psalm-plugin-symfony#109]
#61 added support for Twig taint analysis with two different approaches (file analyzer and cached template files).

According to the pull request, "The two have their own advantages.". Unfortunately, it is not documented what the differences and  advantages are of each approach.

**Comment by seferov** [comment]
@adrienlucas could you please help with this?

**Comment by adrienlucas** [comment]
@seferov @micheh yep, i'll take some time this week to explain the two approaches in the documentation !

**Comment by adrienlucas** [comment]
@micheh please check out https://github.com/psalm/psalm-plugin-symfony/pull/121 and let me know if you find it sufficiently useful or if it stills lake some informations you would like !
