### ISSUE TITLE
Crash v2.2 in Alpine Linux

### ISSUE THREAD

**Issue by alexandrbarabolia** [psalm/psalm-plugin-symfony#152]
Hi. I have a problem when upgrading to version 2.2 on Alpine Linux in Docker images 
php-cli-8.0-alpine, problem next :

Uncaught Error: Undefined constant "GLOB_BRACE" in /app/vendor/psalm/plugin-symfony/src/Plugin.php:36
Stack trace:
#0 /app/vendor/psalm/plugin-symfony/src/Plugin.php(89): Psalm\SymfonyPsalmPlugin\Plugin->getCommonStubs()
#1 /app/vendor/vimeo/psalm/src/Psalm/Config.php(1146): Psalm\SymfonyPsalmPlugin\Plugin->__invoke(Object(Psalm\PluginRegistrationSocket), Object(SimpleXMLElement))
#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(585): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#3 /app/vendor/vimeo/psalm/src/psalm.php(683): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/', true)
#4 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#5 {main}

Next Psalm\Exception\ConfigException: Failed to load plugin Psalm\SymfonyPsalmPlugin\Plugin in /app/vendor/vimeo/psalm/src/Psalm/Config.php:1148
Stack trace:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(585): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#1 /app/vendor/vimeo/psalm/src/psalm.php(683): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/', true)
#2 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#3 {main}
(Psalm 4.6.2@bca09d74adc704c4eaee36a3c3e9d379e290fc3b crashed due to an uncaught Throwable)

I think, this happens because this const doesn't isset in this linux dist. I find similar problem in Symfony 4 https://github.com/symfony/symfony/commit/d7a06790119b04e4f3e96f36dbf68e70ec5964ae .

Help me, please.

**Comment by seferov** [comment]
@alexandrbarabolia thank you for the report. It is fixed with https://github.com/psalm/psalm-plugin-symfony/pull/153
