### ISSUE TITLE
How to get correct form type in controller

### ISSUE THREAD

**Issue by zmitic** [psalm/psalm-plugin-symfony#155]
For a form like this:

```php
/**
 * @extends AbstractType<Customer>
 */
class CustomerFormType extends AbstractType
```

and controller like this (removed the irrelevant parts):

```php
public function __invoke(): Response
{
    $form = $this->createForm(CustomerFormType::class);
    $data = $form->getData();
    /** @psalm-trace $data */
```

I get ``mixed`` instead of ``?Customer``. 

Is this something that can be resolved by psalm stubs? Not all tags are documented (like proxy) and I would prefer stub over plugin.

**Comment by andrew-demb** [comment]
Check documentation for templates and class-string - https://psalm.dev/docs/annotating_code/templated_annotations/#param-class-stringt

**Comment by zmitic** [comment]
@andrew-demb It is not the issue, let me show simpler example. If I trace ``$form``, I get

```
$form: Symfony\Component\Form\FormInterface
```

What I should be getting is 

``` 
$form: Symfony\Component\Form\FormInterface<Customer>
```

So: 

stub should read the template value (Customer) from class itself.

**Comment by andrew-demb** [comment]
You can try with something like this:
```php
/**
 * @template TData
 * @template TFormType of FormTypeInterface<TData>
 *
 * @param class-string<TFormType> $type
 *
 * @return FormInterface<TData>
 */
function createForm(string $type, $data = null, array $options = []): FormInterface
{
}
```

https://psalm.dev/r/ef9c7074e1

**Comment by zmitic** [comment]
@andrew-demb You are a genius, thank you!

PS:
No, it doesn't work on my project (still mixed) but I will find a way hopefully. It works on psalm.dev so there is some bug on my end.

But the idea you put is just amazing.

**Comment by zmitic** [comment]
@andrew-demb 

I can write those tests (I think I got around that) and send you to make PR; you deserve the credit.
