### ISSUE TITLE
Invalid check for FormConfigBuilderInterface::addEventListener

### ISSUE THREAD

**Issue by pkly** [psalm/psalm-plugin-symfony#190]
If one adds an event via closure for the POST_SUBMIT event psalm will incorrectly mark it as an error, expecting a callable with PreSetDataEvent/PostSetDataEvent/SubmitEvent
But there's also PostSubmitEvent (at least in 4.4+), which should be added to the list.

**Comment by zmitic** [comment]
@seferov Want me to take a look at that?

**Comment by seferov** [comment]
@zmitic yes, please. Thank you

**Comment by zmitic** [comment]
@seferov Done, but some tests are failing not related to this issue.
