### ISSUE TITLE
InputOption::VALUE_OPTIONAL can be null, even if a default value is provided.

### ISSUE THREAD

**Issue by VincentLanglet** [psalm/psalm-plugin-symfony#195]
With the following configuration of the command,
```
->addOption('force', 'f', InputOption::VALUE_OPTIONAL, '', 'defaultValue');
```

When running the command the option `force` is `'defaultValue'` by default. 
If I run the same command with `--force=foo`, the option `force` will be `'foo'`.
But I can also run the command with `--force`, and then the option will be `null`.

So I think we should not remove `null` from the return types
https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Handler/ConsoleHandler.php#L192

I can do the PR if you agree with this @seferov

**Comment by seferov** [comment]
@VincentLanglet yes, completely agree. Thank you.
