### ISSUE TITLE
InputBag `get` can return other types than `string`.

### ISSUE THREAD

**Issue by VincentLanglet** [psalm/psalm-plugin-symfony#199]
The following code
```
(string) $request->query->get('foo');
(string) $request->request->get('bar');
```
Is giving errors `RedundantCastGivenDocblockType`.

In this PR, return type of `get` was changed from `string|null` to `string|int|float|bool|null`
https://github.com/symfony/symfony/commit/381a0a19f741da314dff99fc64cc75d674fc7beb#diff-94e19ba3b933d919da3a23761ecef19e001863c18676880231d420d60fa6a142R28

So this stub need to be updated
https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Stubs/5/InputBag.stubphp
Seems like you introduced it @seferov ; do you agree ?

If I understand correctly the template, it need to be updated from
```
@template D of string|null
@psalm-param D $default
@psalm-return string|D
```
to
```
@template D of string|int|float|bool|null
@psalm-param D $default
@psalm-return string|int|float|bool|D
```

**Comment by seferov** [comment]
@VincentLanglet thanks for the report. Yes, stubs needs to be updates as you suggested.

**Comment by VincentLanglet** [comment]
Done https://github.com/psalm/psalm-plugin-symfony/pull/200
