### ISSUE TITLE
Cannot find file `../var/cache/prod/App_KernelProdContainer.preload.php`

### ISSUE THREAD

**Issue by ThomasLandauer** [psalm/psalm-plugin-symfony#205]
This might be related to https://github.com/psalm/psalm-plugin-symfony/issues/201 - another Symfony 5.3 configuration issue. I'm getting:

> MissingFile - config/preload.php:4:5 - Cannot find file ../var/cache/prod/App_KernelProdContainer.preload.php to include

This is `config/preload.php`:

```php
<?php declare(strict_types=1);

if (file_exists(dirname(__DIR__).'/var/cache/prod/App_KernelProdContainer.preload.php')) {
    require dirname(__DIR__).    '/var/cache/prod/App_KernelProdContainer.preload.php';
}
```
I think that psalm is running in dev environment (`<containerXml>var/cache/dev/App_KernelDevDebugContainer.xml</containerXml>`), and indeed the referenced `App_KernelProdContainer.preload.php` does not exist. But `file_exists()` should take care of that, shouldn't it?

**Comment by seferov** [comment]
@ThomasLandauer it is related to https://github.com/vimeo/psalm/issues/3886

I think it is best to add this to psalm.xml
```xml
<issueHandlers>
    <MissingFile>
        <errorLevel type="suppress">
            <directory name="var/cache/dev/Symfony" />
        </errorLevel>
    </MissingFile>
</issueHandlers>
```
