### ISSUE TITLE
Discussion about stubs

### ISSUE THREAD

**Issue by zmitic** [psalm/psalm-plugin-symfony#209]
Starting next week, I will have more time to make stubs. But Symfony is big, really big. You just won't believe how vastly hugely mind-bogglingly big it is.

Putting stubs [in one folder](https://github.com/psalm/psalm-plugin-symfony/tree/master/src/Stubs/common) makes it harder to find them; it could easily end in hundreds of files there.

Even bigger problem will happen when there are 2 files with the same name, but used in different namespace; take this example:

``Symfony\Component\HttpKernel\Log\Logger`` and ``Symfony\Bridge\Monolog\Logger``

With current organization, we would have to make a file like ``MonologLogger.stubphp``; not very friendly.

**Proposal:**

create stubs to match their namespaces. Even if there is just one file inside some folder at the beginning, with time, new stubs will be added.

``common`` folder would be a place that is used for ``Symfony`` namespace. There are some files there that doesn't use ``Component`` namespace so another folder would be created.

---

What do you think?

**Comment by seferov** [comment]
@zmitic hello, thanks for your suggestion.
 
Actually I was planning to do the exact same thing. Good news is that it should be really easy to organize stubs under respective folders without doing any refactoring.

Note about `common` folder, it means common for all supported versions (4, 5 and there will be 6). For each version folders, the structure should be exactly the same.

**Comment by zmitic** [comment]
>Note about common folder, it means common for all supported versions

This folder is the one I wanted to discuss; what about components and the example of ``Logger`` that is both in S4 and S5?

For example: 
what would be the folder structure for [http-foundation](https://github.com/symfony/http-foundation), assuming all files are stubbed (in time)? We have 3 of them stubbed ATM but there is much more.

Please put it here and I will follow it. Today I found lots of form files are not stubbed (like ``ChoiceList`` in 2 different namespaces), data-mappers etc...


>Actually I was planning to do the exact same thing

Any ETA? I have few stubs waiting and from my past experience with git merge, I would really rather not go thru that again :smile: 

---

Also: 

we could split the job.
