### ISSUE TITLE
Psalm now fails with Symfony v3

### ISSUE THREAD

**Issue by edhgoose** [psalm/psalm-plugin-symfony#214]
We're getting the following exception while running psalm with the psalm-plugin-symfony for Symfony 3.

This is because the changes in https://github.com/psalm/psalm-plugin-symfony/pull/210 don't find a folder for version 3 (`/home/vendor/psalm/plugin-symfony/src/Stubs/3`). I think it'd fail for any other version outside of 4 and 5 too.

Here's the exception:

```
Scanning files...
Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/vendor/psalm/plugin-symfony/src/Stubs/3): failed to open dir: No such file or directory in /home/vendor/psalm/plugin-symfony/src/Plugin.php:106
Stack trace:
#0 /home/vendor/psalm/plugin-symfony/src/Plugin.php(106): RecursiveDirectoryIterator->__construct('/home/...')
#1 /home/vendor/psalm/plugin-symfony/src/Plugin.php(74): Psalm\SymfonyPsalmPlugin\Plugin->addStubs(Object(Psalm\PluginRegistrationSocket), '/home/...')
#2 /home/vendor/vimeo/psalm/src/Psalm/Config.php(1273): Psalm\SymfonyPsalmPlugin\Plugin->__invoke(Object(Psalm\PluginRegistrationSocket), NULL)
#3 /home/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(592): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#4 /home/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/...', false)
#5 /home/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#6 {main}

Next Psalm\Exception\ConfigException: Failed to load plugin Psalm\SymfonyPsalmPlugin\Plugin in /home/vendor/vimeo/psalm/src/Psalm/Config.php:1275
Stack trace:
#0 /home/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(592): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#1 /home/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/...', false)
#2 /home/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#3 {main}
(Psalm 4.9.3@4c262932602b9bbab5020863d1eb22d49de0dbf4 crashed due to an uncaught Throwable)
```

**Comment by seferov** [comment]
@edhgoose thanks for the report. Actually starting from version 3, Symfony 3 is not supported anymore. I forgot to restrict through composer constraints. I will update it.

**Comment by sjparkinson** [comment]
> Actually starting from version 3, Symfony 3 is not supported anymore. I forgot to restrict through composer constraints. I will update it.

Worth highlighting that https://github.com/psalm/psalm-plugin-symfony/pull/138 introduced some incompabilities with Symfony 3 in v2 of this plugin. For example, [`Form.stubphp`](https://github.com/psalm/psalm-plugin-symfony/pull/138/files#diff-06ed4137c3f17c8dcb4e5d0ac3004fb149895261c7aba455e19befa7f46933b1) inherits `ClearableErrorsInterface` which doesn't exist in Symfony 3.4.

Seems like v2.1.2 might be the best version of this plugin to use for projects still running Symfony 3.
