### ISSUE TITLE
DataTransformerInterface is buggy

### ISSUE THREAD

**Issue by VincentLanglet** [psalm/psalm-plugin-symfony#223]
Hi @seferov 

With the following code
```
final class BooleanTypeToBooleanTransformer implements DataTransformerInterface
{
    public function transform($value): ?int
    {
        if (true === $value || BooleanType::TYPE_YES === (int) $value) {
            return BooleanType::TYPE_YES;
        } elseif (false === $value || BooleanType::TYPE_NO === (int) $value) {
            return BooleanType::TYPE_NO;
        }

        return null;
    }

    public function reverseTransform($value): ?bool
    {
        if (BooleanType::TYPE_YES === $value) {
            return true;
        } elseif (BooleanType::TYPE_NO === $value) {
            return false;
        }

        return null;
    }
}
```

I get
```
ERROR: InvalidReturnType - src/DataTransformer/BooleanTypeToBooleanTransformer.php:21:40 - The declared return type 'null' for Sonata\Form\DataTransformer\BooleanTypeToBooleanTransformer::transform is incorrect, got '1|2|null' (see https://psalm.dev/011)
    public function transform($value): ?int


ERROR: InvalidReturnStatement - src/DataTransformer/BooleanTypeToBooleanTransformer.php:24:20 - The inferred type '1' does not match the declared return type 'null' for Sonata\Form\DataTransformer\BooleanTypeToBooleanTransformer::transform (see https://psalm.dev/128)
            return BooleanType::TYPE_YES;


ERROR: InvalidReturnStatement - src/DataTransformer/BooleanTypeToBooleanTransformer.php:26:20 - The inferred type '2' does not match the declared return type 'null' for Sonata\Form\DataTransformer\BooleanTypeToBooleanTransformer::transform (see https://psalm.dev/128)
            return BooleanType::TYPE_NO;


ERROR: InvalidReturnType - src/DataTransformer/BooleanTypeToBooleanTransformer.php:32:47 - The declared return type 'null' for Sonata\Form\DataTransformer\BooleanTypeToBooleanTransformer::reverseTransform is incorrect, got 'bool|null' (see https://psalm.dev/011)
    public function reverseTransform($value): ?bool


ERROR: InvalidReturnStatement - src/DataTransformer/BooleanTypeToBooleanTransformer.php:35:20 - The inferred type 'true' does not match the declared return type 'null' for Sonata\Form\DataTransformer\BooleanTypeToBooleanTransformer::reverseTransform (see https://psalm.dev/128)
            return true;


ERROR: FalsableReturnStatement - src/DataTransformer/BooleanTypeToBooleanTransformer.php:37:20 - The declared return type 'null' for Sonata\Form\DataTransformer\BooleanTypeToBooleanTransformer::reverseTransform does not allow false, but the function returns 'false' (see https://psalm.dev/137)
            return false;
```

If I remove the symfony plugin, I don't have the error. 
If I manually remove the DataTransformerInterface stub from my vendor, I don't have the error either.

I'm not sure there is some interest to keep this stub.

**Comment by VincentLanglet** [comment]
There might be some interest with this stub then. 

But I still think something is buggy because, even without adding the `@implements` tag, I should not end with message
```
The inferred type ... does not match the declared return type 'null'
```
since the return type I declared is not `null`.

**Comment by orklah** [comment]
The @implement is needed yeah.

What seem to be the issue here is that Psalm must consider that the template is empty, so you end up with a return `empty|null` which is `null`, so Psalm expects you to return null only.

PHPStan actually emit a issue saying you have to put the @implements

**Comment by VincentLanglet** [comment]
> The @implement is needed yeah.

Would it be possible to make it optional ?

**Comment by zmitic** [comment]
https://psalm.dev/r/28fadfd467

Don't add your own return typehints, use generics if needed. Transformer methods are doing opposite things; what one returns other gets and vice-versa.

That is why there are only 2 generic params, not 4.

**Comment by VincentLanglet** [comment]
> Don't add your own return typehints, use generics if needed.

I agree generic solve a lot of use case. And might be useful here.
But it shouldn't forbid to use return typehint too if I'm in a situation I can add them.

**Comment by zmitic** [comment]
>But it shouldn't forbid to use return typehint too if I'm in a situation I can add them.

Then use ``@implements DataTransformerInterface<mixed, mixed>``

You should not add your own ``@param``, their values are resolved via generics in interface.

**Comment by VincentLanglet** [comment]
> Then use `@implements DataTransformerInterface<mixed, mixed>`

The issue is that psalm arbitrary introduce a generic which wasn't introduced by other static analysis tool like PHPStan.
Which means that if I do this, I'll end with a PHPStan error `DataTransformerInterface is not generic`.

**Comment by orklah** [comment]
How does PHPStan's symfony plugin solved this?

**Comment by VincentLanglet** [comment]
> How does PHPStan's symfony plugin solved this?

PHPStan just does not provide any stub for the DataTransformerInterface
https://github.com/phpstan/phpstan-symfony/tree/master/stubs/Symfony/Component/Form

So an error `transform() should be contravariant` is thrown when another phpdoc than `mixed` is used.
Might be a feature request for phpstan then.
