### ISSUE TITLE
UndefinedMagicMethod for Doctrine Repository

### ISSUE THREAD

**Issue by michnovka** [psalm/psalm-plugin-symfony#250]
Getting errors for my magic methods:

```
ERROR: UndefinedMagicMethod - src/Controller/CP/Settings/AdminController.php:59:57 - Magic method App\Repository\AdminRepository::findonebyemail does not exist (see https://psalm.dev/219)
            $findAdminByEmail = $this->adminRepository->findOneByEmail($adminMail);
```

the code for repository is the standard one generated by `make:entity`:

```php
/**
 * @method admin|null find($id, $lockMode = null, $lockVersion = null)
 * @method admin|null findOneBy(array $criteria, array $orderBy = null)
 * @method admin[]    findAll()
 * @method admin[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class AdminRepository extends ServiceEntityRepository implements PasswordUpgraderInterface
```

**Comment by zmitic** [comment]
This method actually doesn't exist, it is only supported by magic ``__call`` method in ``EntityRepository`` class.

So you need to either put that method in those phpdocs, or not use it at all (preferable, magic is always bad). Or you make one by yourself.

---

A bit offtopic:

Doctrine has been psalmified for some time which means you have to do this:


```php
/**
 * @extends ServiceEntityRepository<User>
 */
class AdminRepository extends ServiceEntityRepository implements PasswordUpgraderInterface

```


or psalm will report errors. At least it happens on level 1 and no mixed. PHPStorm (latest version) understand generics used and will autocomplete templated methods.
