### ISSUE TITLE
Symfony's FrameworkConfig methods not found

### ISSUE THREAD

**Issue by ThomasLandauer** [psalm/psalm-plugin-symfony#256]
Symfony changed its configuration recently - see https://github.com/symfony/symfony/issues/46546

psalm is now reporting:

> PossiblyUndefinedMethod - config/packages/framework.php - Method Symfony\Config\FrameworkConfig::scopedClient does not exist

So the workaround (`<extraFiles>`) I added in https://github.com/psalm/psalm-plugin-symfony/pull/203 isn't working anymore.

Is there a change that this can get fixed in psalm? If no, I'd delete that workaround from the docs again, and recommend to exclude `config/` from analysis (as recommended in the linked Symfony issue).

**Comment by seferov** [comment]
@ThomasLandauer it seems there is a second thought on it https://github.com/symfony/symfony/issues/46546#issuecomment-1146637184
https://github.com/symfony/symfony/pull/46581 might fix the issue

**Comment by ThomasLandauer** [comment]
Indeed, this works now (Symfony 6.2), so I'm closing this.

**Comment by arderyp** [comment]
I'm confused. It works in Symfony 6.2, but what about those of us on 5.4?
