### ISSUE TITLE
Uncaught Exception: Error Undefined constant DBTrait::REPOSITORY_CLASS

### ISSUE THREAD

**Issue by mathroc** [psalm/psalm-plugin-symfony#257]
Uncaught Exception: Error Undefined constant MyTrait::REPOSITORY_CLASS
Emitted in /var/www/vendor/psalm/plugin-symfony/src/Handler/ContainerHandler.php:105

It's caused by this code:

```php
trait DBTrait
{
    public function getDB(): ConnectionInterface
    {
            return self::$container->get(self::REPOSITORY_CLASS)->db();
    }
}
```

I don't know what the plugin should/can do in this case but at least it should not crash

**Comment by seferov** [comment]
@mathroc thanks for the report!

Could you please provide a test case in a separate scenario to reproduce the issue? You can add it and see examples here https://github.com/psalm/psalm-plugin-symfony/blob/master/tests/acceptance/acceptance/ContainerService.feature

I failed to reproduce it.

**Comment by mathroc** [comment]
well, I can't reproduce it anymore either :shrug: neither with the sample code from the issue description nor with the codebase it was crashing on before..

I'll close this issue and reopen it if it happens again
