### ISSUE TITLE
ConsoleHandler: Undefined property: PhpParser\Node\Expr\Variable::$value

### ISSUE THREAD

**Issue by gharlan** [psalm/psalm-plugin-symfony#26]
I'm trying to enable the plugin on https://github.com/redaxo/redaxo (for the console handler).

![Screenshot 2020-04-26 13 25 47](https://user-images.githubusercontent.com/330436/80306119-96671f80-87c1-11ea-95fa-79777c181d9f.png)

The warning is coming from this line: 
https://github.com/psalm/psalm-plugin-symfony/blob/131c7a04f5777e2c9867e823345e7203829d8dd5/src/Handler/ConsoleHandler.php#L70

**Comment by seferov** [comment]
@gharlan thank you for the report. https://github.com/psalm/psalm-plugin-symfony/pull/27 should fix it
