### ISSUE TITLE
Psalm-suppress annotations are ignored

### ISSUE THREAD

**Issue by rvveber** [psalm/psalm-plugin-symfony#278]
Please see the content of this issue:
https://github.com/vimeo/psalm/issues/8596

**Comment by kkmuffme** [comment]
Just create a PR, this is something you can easily fix yourself

**Comment by rvveber** [comment]
> Just create a PR, this is something you can easily fix yourself

First you say issue, now PR..
I don't have the time to fix this

**Comment by kkmuffme** [comment]
Everybody who contributes to open source has other things to do too and "no time to fix this"; we all have families, kids, a job,... too.

This is a very simple issue that shouldn't take you longer than 30 mins to figure out, when you have never worked in the psalm code base. It's a great way to get you started contributing to free open source software.

**Comment by seferov** [comment]
@color-space 

There is a passing test for this case: suppressing ContainerDependency issue:

https://github.com/psalm/psalm-plugin-symfony/blob/v3.1.9/tests/acceptance/acceptance/ContainerDependency.feature#L28-L42

Can you create a scenario where it fails to reproduce it?

**Comment by rvveber** [comment]
@seferov 

1. I'm using the "dockware/dev" docker image as a base.
2. Ontop i install `psalm/plugin-symfony` globally with composer
4. `sudo ln -s /var/www/.composer/vendor/bin/psalm /usr/local/bin/psalm`
`sudo ln -s /var/www/.composer/vendor/bin/psalm-plugin /usr/local/bin/psalm-plugin`
5. I configure my psalm.xml in ~/html like this:
```xml
<?xml version="1.0"?>
<psalm autoloader="./vendor/autoload.php" errorLevel="2" resolveFromConfigFile="true" phpVersion="8.1">
    <plugins>
        <pluginClass xmlns="https://getpsalm.org/schema/config" class="Psalm\SymfonyPsalmPlugin\Plugin" />
    </plugins>

    <projectFiles>
        <directory name="custom/plugins" />
    </projectFiles>

    <issueHandlers>
        <PropertyNotSetInConstructor>
            <errorLevel type="suppress">
                <directory name="*" />
            </errorLevel>
        </PropertyNotSetInConstructor>
    </issueHandlers>
</psalm>
```
5. `bin/console plugin:create TestPlugin` to create a shopware plugin in `~\html\custom\plugins\TestPlugin`, in the plugin class (TestPlugin.php), create a "install" method, in it pass the $this->container to a new class that accepts it as an argument. 
6. Add the annotation above the declaration of the argument in the new class
7. in ~/html execute `psalm --php-version=8.1`
8. Result in my case (Pluginclass is "Lesefix" and class that accepts the container as an argument is "InstallUninstall")
![image](https://user-images.githubusercontent.com/8644906/196385100-8adf8f72-9b98-4d4d-98bd-1f7472db3132.png)


Reason that i can't use the dependency injection there:
The dependency system is not yet loaded at the install hook, therefore i  can't register my InstallUninstall as a service

**Comment by seferov** [comment]
@color-space can you please share the content of `TestPlugin`?

**Comment by rvveber** [comment]
@seferov 

TestPlugin:
```php
<?php declare(strict_types=1);

namespace TestPlugin;

use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;

class TestPlugin extends Plugin
{
    public function install(InstallContext $installContext): void
    {
        parent::install($installContext);
        new InstallUninstall($this->container);
    }
}
```
InstallUninstall:
```php
<?php

namespace TestPlugin;

use Symfony\Component\DependencyInjection\ContainerInterface;

class InstallUninstall{

    public function __construct(
        /** @psalm-suppress ContainerDependency */
        ContainerInterface $container
    ){}
}
```

**Comment by rvveber** [comment]
I think the problem is the location of my docblock.
When i specify it above the __construct it seems to work, but doesn't that suppress protential errors for the whole function?
I guess if scoping by variable works here too, which seems to be the case, then a 
```php
/** @psalm-suppress ContainerDependency $container*/
public function __construct(
...
```
would work. 
I just wonder if this is considered an incorrect and non-detectable docblock, or if this was not considered by this plugin.

**Comment by rvveber** [comment]
Pretty sure my docblock was just incorrect. closing
