### ISSUE TITLE
Undefined property: PhpParser\Node\Expr\Variable::$value

### ISSUE THREAD

**Issue by bendavies** [psalm/psalm-plugin-symfony#28]
```
PHP Notice:  Undefined property: PhpParser\Node\Expr\Variable::$value in .../vendor/psalm/plugin-symfony/src/Handler/ConsoleHandler.php on line 70
```

I think the happens if the code is something like `$input->getOption($name)`

**Comment by seferov** [comment]
@bendavies thank you for the report. It was fixed with this https://github.com/psalm/psalm-plugin-symfony/pull/27
Could you please update it to v1.2.1?
