### ISSUE TITLE
Default repo branch

### ISSUE THREAD

**Issue by seferov** [psalm/psalm-plugin-symfony#281]
@weirdan @muglug could you please update default branch to `4.x`? After that `master` branch can be deleted.

**Comment by weirdan** [comment]
Got the following warning:

> The branch **master** is associated with 5 open pull requests:
>
>    [#142 - Prevent PropertyNotSetInConstructor](https://github.com/psalm/psalm-plugin-symfony/pull/142)
>    [#248 - Templated ServiceLocator to be used for tagged services](https://github.com/psalm/psalm-plugin-symfony/pull/248)
>    [#253 - Stubs for extended form types](https://github.com/psalm/psalm-plugin-symfony/pull/253)
>
> and 2 more
>
> If you delete this branch, the pull requests will be closed.
>
> Are you sure you want to delete this branch?

**Comment by weirdan** [comment]
The default branch has been changed though.

**Comment by seferov** [comment]
@weirdan Ok, lets keep `master` branch for now.


> The default branch has been changed though.

Thank you!
