### ISSUE TITLE
Support Psalm 5

### ISSUE THREAD

**Issue by schodemeiss** [psalm/psalm-plugin-symfony#285]
Now Psalm has hit a RC of version 5.0.0 (https://github.com/vimeo/psalm/releases/tag/5.0.0-rc1), it'd be great if this plugin supported it.

Unfortunately, Symfony 6.2 has some updates to it's UID component ([Factory/TimeBasedUuidFactory.php](https://github.com/symfony/uid/blob/6.2/Factory/TimeBasedUuidFactory.php)) which use intersection types, which Psalm 4 doesn't support; but Psalm 5 does.

**Comment by schodemeiss** [comment]
Now **out** of RC: https://github.com/vimeo/psalm/releases/tag/5.0.0

**Comment by michnovka** [comment]
does this make psalm completely unusable with symfony 6.2? I am getting fatal exceptions thrown when I use 4.30

**Comment by schodemeiss** [comment]
Yes. Psalm 4 does not support the intersection type declared in version 6.2 of the UID component. Hence requiring to go up to Psalm 5 which does support intersection types.

I'm having to lock UID at v6.1 at the moment because I can't upgrade Psalm primarily because this plugin doesn't support Psalm 5. As soon as it does, we can upgrade all the things.

**Comment by seferov** [comment]
Thanks for the report.
@schodemeiss @michnovka @danog
https://github.com/psalm/psalm-plugin-symfony/releases/tag/v5.0.0 was released.
