### ISSUE TITLE
PossiblyUnusedMethod __construct for dependency injected classes

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [psalm/psalm-plugin-symfony#291]
I have a symfony project and just started to use psalm and this plugin.
I activated 
`  findUnusedCode="true"`
and now have dozens of false posives, like
```
ERROR: PossiblyUnusedMethod - src/Service/DataService/MedicationBuilder.php:18:21 - Cannot find any calls to method App\Service\DataService\MedicationBuilder::__construct (see https://psalm.dev/087)
    public function __construct(
```
is this something this plugin should handle?

**Comment by seferov** [comment]
@OwnerOfThisIsle thanks for the report! Yes, plugin handles such errors if you configured containerXml. Please see https://github.com/psalm/psalm-plugin-symfony#configuration
Feel free to reopen the issue with more details if you still have the error.

**Comment by OwnerOfThisIsle** [comment]
I was not clear about this:
I am **already** using the psalm-plugin-symfony and followed the configuration instructions.
I think it is **partly working** because **without the plugin config psalm reports some additional errors** (PropertyNotSetInConstructor, PossiblyInvalidArgument, UndefinedDocblockClass), but still **with** the plugin and that configuration:
```
<plugins>
      <pluginClass class="Psalm\SymfonyPsalmPlugin\Plugin">
          <containerXml>var/cache/dev/App_KernelDevDebugContainer.xml</containerXml>
          <containerXml>var/cache/test/App_KernelTestDebugContainer.xml</containerXml>
      </pluginClass>
</plugins>
```
there are plenty PossiblyUnusedMethod Errors (as mentioned in more detail in the question above).
They are dependency injected classes, so there is no call to their constructor.
