### ISSUE TITLE
Symfony's Configurator functions `env()` and `param()` not found

### ISSUE THREAD

**Issue by ThomasLandauer** [psalm/psalm-plugin-symfony#292]
I'm getting:
> ERROR: UndefinedFunction - config/packages/mailer.php:12:54 - Function Symfony\Component\DependencyInjection\Loader\Configurator\\**env** does not exist (see https://psalm.dev/021)

> ERROR: UndefinedFunction - config/packages/monolog.php:38:16 - Function Symfony\Component\DependencyInjection\Loader\Configurator\\**param** does not exist (see https://psalm.dev/021)

even though I have this in the config files:
```php
use function Symfony\Component\DependencyInjection\Loader\Configurator\env;
use function Symfony\Component\DependencyInjection\Loader\Configurator\param;
```

The file from Symfony is looking like this:
```php
<?php

namespace Symfony\Component\DependencyInjection\Loader\Configurator;

class ContainerConfigurator extends AbstractConfigurator
{
    // ...
}

function param(string $name): ParamConfigurator
{
    // ...
}

function env(string $name): EnvConfigurator
{
    // ...
}
```
There was a similar issue in PHPStan, and the answer was that this doesn't comply to PSR-4: https://github.com/phpstan/phpstan/issues/5189#issuecomment-863821592

Is there a solution or a workaround?

**Comment by weirdan** [comment]
Are these functions supposed to be globally available?

**Comment by ThomasLandauer** [comment]
Well, at least in Symfony's config files, see e.g. https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables
```php
'url' => env('DATABASE_URL')->resolve(),
```

**Comment by weirdan** [comment]
Then I believe the easiest workaround is to add that file as a stub in `psalm.xml`:
```xml
<stubs>
   <file name="vendor/symfony/....">
</stubs>
```

**Comment by ThomasLandauer** [comment]
Thanks  - works - I added it to README, since (sooner or later) most Symfony users will need it: https://github.com/psalm/psalm-plugin-symfony/pull/297
