### ISSUE TITLE
Support reduced type inferring from Collection::filter

### ISSUE THREAD

**Issue by ostrolucky** [psalm/psalm-plugin-symfony#30]
Plugin should add capability to infer reduced type from `Collection::filter` based on assertions in a callback, similarly as Psalm currently does for `array_filter`. Here is what should be supported: https://psalm.dev/r/1b5cbdc9c0

Backstory: From conversation with @muglug:

> Add that to the doctrine plugin
>
> This is the current annotation: https://github.com/doctrine/collections/blob/a4504c79efd8847cc77d10b70209ef838b10338f/lib/Doctrine/Common/Collections/Collection.php#L214-L225
>
> there’s basically no way to annotate that in a docblock

**Comment by seferov** [comment]
Thank you for the report. I am not sure whether this plugin should do Doctrine related issues.
There is a dedicated plugin for Doctrine https://github.com/weirdan/doctrine-psalm-plugin/
Maybe this plugin can be recommended in the README since most of the Symfony apps using Doctrine.

**Comment by ostrolucky** [comment]
Ah indeed, I created this in wrong repository
