### ISSUE TITLE
Error type form: FormType cannot be cast to string

### ISSUE THREAD

**Issue by Myks92** [psalm/psalm-plugin-symfony#302]
When calling the method `сreateForm()` in stubs [AbstractController](https://github.com/psalm/psalm-plugin-symfony/blob/83ede57320c4dc6d07cfabe8b76cd28164c9ee8d/src/Stubs/6/Bundle/FrameworkBundle/Controller/AbstractController.stubphp#L26), the type changes from string to object and call the error "The form type cannot be converted to a string"

Example: https://psalm.dev/r/885549f5ec

**Comment by zmitic** [comment]
It is a bug in psalm itself: https://github.com/vimeo/psalm/issues/8810#issuecomment-1334660765

**Comment by Myks92** [comment]
Ok. I thought this problem is in the Symfony plugin, because not call the error without Symfony plugin. Looking forward to fixing it. Thanks!

**Comment by Myks92** [comment]
Done: https://github.com/vimeo/psalm/issues/8810
