### ISSUE TITLE
Default repo branch

### ISSUE THREAD

**Issue by seferov** [psalm/psalm-plugin-symfony#327]
@weirdan could you please update default branch for the repository to `5.x`?

The other issue is the removal of wrong version ([v5.04](https://packagist.org/packages/psalm/plugin-symfony#v5.04)) from packagist. There is a typo in the version. Composer takes it as priority even if there are higher versions

![image](https://github.com/psalm/psalm-plugin-symfony/assets/1233843/b37982a9-da70-4c17-8b89-c5b6b6189de2)

**Comment by weirdan** [comment]
@psalm/maintainers should be able to do this.

**Comment by weirdan** [comment]
5.x is now a default branch.

**Comment by weirdan** [comment]
re 5.04 - I don't see it on packagist anymore. Someone must have fixed that already.

**Comment by seferov** [comment]
@weirdan thank you
