### ISSUE TITLE
[Symfony 7.1] You have requested a non-existent service "kernel::registerContainerConfiguration()

### ISSUE THREAD

**Issue by sidz** [psalm/psalm-plugin-symfony#336]
Hey.
Symfony 7.1 has been released today but this plugin is not compatible with it:

![image](https://github.com/psalm/psalm-plugin-symfony/assets/1302230/f596c993-0890-4dcb-90c7-25836c8e421f)

**Comment by ostrolucky** [comment]
@nicolas-grekas I've tracked this to https://github.com/symfony/http-kernel/commit/a53d83209e8204c579603e396e0a68c7adbeb8ee

**Comment by nicolas-grekas** [comment]
I'd be happy to have a look at a small self-contained reproducer.

**Comment by ostrolucky** [comment]
I've added commit to symfony demo repo which reproduces the issue [demo.zip](https://github.com/user-attachments/files/15551531/demo.zip)

**Comment by seferov** [comment]
@sidz @ostrolucky could you please check it with **v5.2.1**

**Comment by sidz** [comment]
@seferov I could confirm that 5.2.1 works fine. thank you
