### ISSUE TITLE
Typo in git tag for today releases?

### ISSUE THREAD

**Issue by andrew-demb** [psalm/psalm-plugin-symfony#340]
For now, installation of the plugin with version restriction `^5.0` - the composer installs version `v5.04`.

Should `v5.04` be dropped from the repository and from the packagist to fix version resolution in favor of the latest available `v5.1.0`?

![image](https://github.com/psalm/psalm-plugin-symfony/assets/12499813/ed076df7-d163-42bb-b618-7508f427067b)

![image](https://github.com/psalm/psalm-plugin-symfony/assets/12499813/80b5e38c-4810-4094-b6f8-443cf10d018e)

**Comment by andrew-demb** [comment]
https://packagist.org/packages/psalm/plugin-symfony

**Comment by seferov** [comment]
@andrew-demb it is an old issue actually. See https://github.com/psalm/psalm-plugin-symfony/issues/327

@weirdan could you please take a look at it?

**Comment by weirdan** [comment]
I've removed the tag from the GitHub repo. @seferov make sure you also delete it in your working copies, or you may push it again accidentally.

**Comment by seferov** [comment]
@weirdan thank you. I just removed it from my working copy. Btw, I can still see it at packagist.

**Comment by weirdan** [comment]
@seferov I've seen it reappear on Github as well. I suspect you may have pushed it after I removed it, and packagist saw it as well.

Please check the packagist page again after a few hours. 

I also added a custom ruleset for this repository to prevent this tag from being recreated: 

![image](https://github.com/psalm/psalm-plugin-symfony/assets/57403/d63025d6-1404-4711-b9a5-469c9db508e6)

**Comment by weirdan** [comment]
If I understand it correctly, the version should disappear from packagist in a day:
https://github.com/composer/packagist/blob/faea1b54fb52e06b9718b6210623d40c0933785e/src/Package/Updater.php#L274-L295

**Comment by seferov** [comment]
@weirdan I don't know why but it looks like the version is still there

**Comment by weirdan** [comment]
@seferov yeah, it seems it didn't work as I expected, and it needed to be deleted from the packagist site manually (which is done now).

**Comment by weirdan** [comment]
I believe this to be fixed now, and with the rules shown above it should not reoccur (for this broken tag).

**Comment by seferov** [comment]
@weirdan thank you
