### ISSUE TITLE
Access to undefined property ClassConstFetch::$value in ConsoleHandler

### ISSUE THREAD

**Issue by Majkl578** [psalm/psalm-plugin-symfony#35]
Running Psalm on lowest level on PHP 7.4.6 I am getting many of the following errors:

```
Notice: Undefined property: PhpParser\Node\Expr\ClassConstFetch::$value in /app/vendor/psalm/plugin-symfony/src/Handler/ConsoleHandler.php on line 113
```

This seems to originate from Symfony commands with custom arguments or options in such form:
```
$this->addArgument(self::FOO_ARGUMENT_NAME, InputArgument::REQUIRED);
$this->addOption(self::FOO_OPTION_NAME, null, InputOption::VALUE_NONE);
```

More specifically it's caused by the argument or option name being referenced from a constant.

nikic/php-parser: v4.4.0
psalm/plugin-symfony: v1.2.2

**Comment by seferov** [comment]
@Majkl578 thank you for the report. New release should fix it.
