### ISSUE TITLE
Extend from PluginIssue, so I can suppress issues of this plugin

### ISSUE THREAD

**Issue by ostrolucky** [psalm/psalm-plugin-symfony#37]
Suppressing issues in this plugin is currently not possible according manual here: https://github.com/vimeo/psalm/blob/1c3796d2a02f322c36e7a167a2b468556440403f/docs/running_psalm/plugins/authoring_plugins.md#handling-custom-plugin-issues

I believe it's because your issues do not extend from PluginIssue.

Specifically, I want to (temporarily) suppress `ContainerDependency` issue.

**Comment by seferov** [comment]
Thank you for the report.

Could you please check if on dev-master the issue is fixed? Here is the change https://github.com/psalm/psalm-plugin-symfony/pull/38

**Comment by ostrolucky** [comment]
Yep, works!

**Comment by seferov** [comment]
Thank you @ostrolucky
