### ISSUE TITLE
InvalidConsoleOptionValue does not allow combining multiple constants

### ISSUE THREAD

**Issue by addiks** [psalm/psalm-plugin-symfony#43]
When specifying the mode argument for console-input's, the constants can be combined using the `+` operator to have multiple different modes active at the same time. This works because the constants are bit-wise integers and the mode is checked for specific constants by checking if their bit is set in the mode integer:

```php
class InputOption
{
    const VALUE_NONE = 1;
    const VALUE_REQUIRED = 2;
    const VALUE_OPTIONAL = 4;
    const VALUE_IS_ARRAY = 8;
   ...
    public function __construct(string $name, $shortcut = null, int $mode = null, string $description = '', $default = null)
    {
   ...
        if (null === $mode) {
            $mode = self::VALUE_NONE;
        } elseif ($mode > 15 || $mode < 1) {
            throw new InvalidArgumentException(sprintf('Option mode "%s" is not valid.', $mode));
        }
   ...
    public function isValueRequired()
    {
        return self::VALUE_REQUIRED === (self::VALUE_REQUIRED & $this->mode);
    }
   ...
    public function isArray()
    {
        return self::VALUE_IS_ARRAY === (self::VALUE_IS_ARRAY & $this->mode);
    }
```
Yet this plugin does not recognize these combined constants and only allows one constant to be present at a time:
```
ERROR: InvalidConsoleOptionValue - src/Brille24/ProductionBundle/Command/CompareManufacturerCatalogsCommand.php:63:13 - Use Symfony\Component\Console\Input\InputOption constants (see https://psalm.dev/000)
            InputOption::VALUE_REQUIRED + InputOption::VALUE_IS_ARRAY,
```
At the moment the only way to deal with these issues is to suppress them using `psalm-suppress`.

**Comment by seferov** [comment]
Hey,

Thanks for the reporting.
Combining multiple values are actually supported. See https://github.com/psalm/psalm-plugin-symfony/blob/v1.2.3/tests/acceptance/acceptance/ConsoleOption.feature#L53

The correct way to define it https://symfony.com/doc/current/console/input.html#using-command-options

> You can combine VALUE_IS_ARRAY with VALUE_REQUIRED or VALUE_OPTIONAL like this:

```php
$this
    // ...
    ->addOption(
        'colors',
        null,
        InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
        'Which colors do you like?',
        ['blue', 'red']
    )
;
```
