### ISSUE TITLE
Services are wrongly handled as public:true by default

### ISSUE THREAD

**Issue by simonberger** [psalm/psalm-plugin-symfony#59]
The Debug Container reading classes are treating the public attribute as true if not available. In the latest Symfony 5.X releases it should never be false anymore (can't test it right now) after the private attribute had been completely removed.
https://github.com/symfony/dependency-injection/blob/master/Dumper/XmlDumper.php#L111

[Here is the concerning code of this plugin](https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Symfony/ContainerMeta.php#L82)
Symfony 3.3 was the last version producing a XML where missing public attributes had a value of true.

If a detection of the correct value is complicated could we configure it?

**Comment by seferov** [comment]
@simonberger thank you for the report! Will fix it.
