### ISSUE TITLE
Need opinion about stubs for symfony/forms

### ISSUE THREAD

**Issue by zmitic** [psalm/psalm-plugin-symfony#60]
I made (some) stubs for symfony/forms and need opinion if my approach is correct. Simple use-case (shortened, ``Route`` is an entity):

```php
/**
 * @extends AbstractType<Route>
 */
class RouteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $route = $builder->getData(); // <- psalm knows it is Route|null
        $nrOfAssignedRoutes = $this->getNrOfAssignedAddresses($route);
    }

    private function getNrOfAssignedAddresses(?Route $route): int // no issues
    {
        return 42;  // real code removed for simplicity
    }
}
```

Controller usage:

```php
    /** 
     * Injected using ArgumentResolver, removed for simplicity. See old https://github.com/strictify/coding-challenge/blob/symfony-4/src/Controller/Product/CreateAction.php#L38
     *
     * @param FormInterface<RouteEntity> $form
     */
    public function create(FormInterface $form): Response
    {
        if ($form->isSubmitted() && $form->isValid() && $data = $form->getData()) { 
            // psalm knows $data is instance of Route (not null)
            
            // persist, flush, redirect
        }

       // render template
    }
```

Future PHP could be:

```php
    public function create(SubmittedForm<RouteType> $submittedForm): Response
    {
        $data = $submittedForm->getDataOrThrowException(); // returns T
    }
```

Assigning data type on form level also fixes ``buildView`` and ``finishView`` methods.

---

This approach could also detect errors when using this bundle: https://github.com/hitechcoding/strict-form-mapper-bundle/blob/master/docs/accessors.md

```php
$builder->add('type', ChoiceType::class, [
    'get_value' => fn(Route $route) => $route->getType(),  // this can detect error is wrong param is typed
    'update_value' => fn(string $type, Route $route) => $route->setType($type),
]);
```

or with same bundle for [factories](https://github.com/hitechcoding/strict-form-mapper-bundle/blob/master/docs/factory.md):
```php
public function configureOptions(OptionsResolver $resolver): void
{
    $resolver->setDefaults([
        'factory' => fn(string $name, string $type) => new Route($this->security->getAuthCompany(), $name, $type),
    ]);
}
```

or default ``empty_data``:
```php
public function configureOptions(OptionsResolver $resolver): void
{
    $resolver->setDefaults([
        'empty_data' => fn(FormInterface $form) => new Route($this->security->getAuthCompany(), $form->get('name')->getData(), $form->get('type')->getData()),
    ]);
}
```

Because of complexity and power of forms, I am asking if you think this is valid approach or if it can be improved somehow. I was thinking about adding ``$options`` as second generic parameter so

```php
/**
 * @extends AbstractType<Route, array{some_external_parameter: bool}>
 */
class RouteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $externalParameter = $options['some_external_parameter']; // <-- psalm would know it is bool value
    }
} 
```

**Comment by seferov** [comment]
@zmitic Thanks for sharing your code. I think it is a valid approach and the plugin can be extended to handle this as well by checking `data_class` attribute from configureOptions:

```php
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'data_class' => Route::class,
    ]);
}
```

**Comment by zmitic** [comment]
@seferov OK, in next week or so I will make PR.

Can you confirm the idea of second parameter ($options)? My stubs don't use ATM it but with more use-cases, I think it should be there.

It would be better if psalm could support optional generic parameter so it can be skipped if not needed, but even dummy array is not much of an issue.

**Comment by seferov** [comment]
> Can you confirm the idea of second parameter ($options)? My stubs don't use ATM it but with more use-cases, I think it should be there.
>
> It would be better if psalm could support optional generic parameter so it can be skipped if not needed, but even dummy array is not much of an issue.

I not sure about the options argument. Options array is used for passing custom parameters which are changing from entity/form to entity/form

**Comment by zmitic** [comment]
>I not sure about the options argument. Options array is used for passing custom parameters which are changing from entity/form to entity/form

This is what I wanted to discuss. By default, ``FormType`` assign lots of values in ``$options`` already. Form extensions do that as well, different types (like ChoiceType) has different options... so it is not something that only comes from controller like my example. 

- repetition; both ``buildView`` and ``finishView`` uses it and it is the place where ``options`` is much more usable than in ``buildForm()``.

- ``configureOptions(OptionsResolver $resolver)``. It would be possible to validate keys of it. Also usable for this case:

```php
class RouteChoiceType extends AbstractType
{
    private RouteRepository $repository;

    public function __construct(RouteRepository $repository)
    {
        $this->repository = $repository;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $choices = $this->repository->findAll();
        usort($choices, fn(Route $a, Route $b) => strnatcmp($a->getName(), $b->getName()));
        $resolver->setDefaults([
            'placeholder' => '-- Route --',
            'class' => Route::class,
            'choices' => $choices,
            'choice_label' => fn(Route $route) => $route->getName(),
        ]);
    }

    public function getParent(): string
    {
        return EntityType::class;
    }
}
```

I have more use-cases, have an application with **really** complex forms. About 60% are not using ``$options``, 40% uses docblock; I find that a cheat. 

---

If only forms were not so powerful, things would be much easier :smile:

**Comment by seferov** [comment]
@zmitic https://github.com/psalm/psalm-plugin-symfony/compare/master...strictify:symfony-forms seems promising and as you mentioned it would be nice to test it in a real project using Symfony Forms intensively.

There are a number of acceptance tests you can check out https://github.com/psalm/psalm-plugin-symfony/tree/master/tests/acceptance/acceptance. It is better add test for each case that stubs aim to fix.

**Comment by zmitic** [comment]
For next 2-3 days I will be super busy but after that, will have time to put this into real project with lots of dynamic forms (because of events and nullable datas). 

The branch I posted is extracted from current project with some refactorings; still need worst-case scenarios to see if that extraction was good.

**Comment by zmitic** [comment]
Latest update; events are working:

![image](https://user-images.githubusercontent.com/1964158/91563548-58c8fd80-e93f-11ea-88fa-594036da010f.png)

**Comment by zmitic** [comment]
I finally started working (sorry guys) and wrote first test. Before I proceed, can you just take a look at it at: https://github.com/strictify/psalm-plugin-symfony/blob/symfony-forms/tests/acceptance/acceptance/forms/FormType.feature

The reason is I have never used codeception before, PHPStorm is not really helping me setting quick runs as it does with PHPUnit and I am not sure I am following best practices in... well everything.

One of things is that are changed is that I put tests in ``/forms`` subfolder. Reason is that forms are really complex thing to stub so a clean folder might be better.

**Comment by seferov** [comment]
@zmitic thank you for the update. I think organizing tests in subfolders is ok. If it is ready can you please create a pull request?

**Comment by VincentLanglet** [comment]
> I will in a few days; still have some tests failing and can't figure why. And because this would be my first OSS contribution, I want to make it right.

You can open the PR even with the tests failing, and you'll get loooooot of reviewer to help you ;)

**Comment by seferov** [comment]
https://github.com/psalm/psalm-plugin-symfony/pull/138
