### ISSUE TITLE
Add support for test container

### ISSUE THREAD

**Issue by micheh** [psalm/psalm-plugin-symfony#64]
It would be nice to support the test container (`Symfony\Bundle\FrameworkBundle\Test\TestContainer`), which allows to fetch private services for testing.

A use case would be the `Symfony\Bundle\FrameworkBundle\Test\KernelTestCase::$container`. If you currently use this container in the tests, Psalm will report a `PrivateService` issue and will not know the correct type (only `object|null`).

I'm not sure how to do this properly. Maybe the `ContainerHandler` could always set the type, even if the service is not public and then suppress the `PrivateService` manualy for the tests directory?

**Comment by seferov** [comment]
@micheh thanks for the report! I think your suggestion is legit.
