### ISSUE TITLE
Fatal Error in my CI

### ISSUE THREAD

**Issue by marartner** [psalm/psalm-plugin-symfony#80]
`Fatal error: Declaration of Psalm\SymfonyPsalmPlugin\Handler\HeaderBagHandler::getMethodReturnType(Psalm\StatementsSource $source, string $fq_classlike_name, string $method_name_lowercase, array $call_args, Psalm\Context $context, Psalm\CodeLocation $code_location, ?array $template_type_parameters = NULL, ?string $called_fq_classlike_name = NULL, ?string $called_method_name_lowercase = NULL) must be compatible with Psalm\Plugin\Hook\MethodReturnTypeProviderInterface::getMethodReturnType(Psalm\StatementsSource $source, string $fq_classlike_name, string $method_name_lowercase, array $call_args, Psalm\Context $context, Psalm\CodeLocation $code_location, ?array $template_type_parameters = NULL, ?string $called_fq_classlike_name = NULL, ?string $called_method_name_lowercase = NULL): ?Psalm\Type\Union in /github/workspace/vendor/psalm/plugin-symfony/src/Handler/HeaderBagHandler.php on line 27`

The difference seems to be the return type being stricter in the interface.

psalm/psalm-plugin-symfony v1.4.3
CI via psalm/psalm-github-actions@1.0.0

**Comment by seferov** [comment]
@marartner thank you for the report.
Actually this is a problem of psalm-github-actions https://github.com/psalm/psalm-github-actions/issues/13
The docker image always using master branch of psalm which may include breaking changes.

**Comment by marartner** [comment]
Right, I figured it'd have to be something like that; thanks for clarifying.
