### ISSUE TITLE
Add support for default command argument values

### ISSUE THREAD

**Issue by jaikdean** [psalm/psalm-plugin-symfony#81]
This plugin doesn't currently seem to handle default argument values in commands. For example, the following will cause Psalm to throw `ERROR: PossiblyNullArgument - … - Argument 1 of trim cannot be null, possibly null value provided (see https://psalm.dev/078)`, even though that argument can never be null, as far as I'm aware.

```php
class FooCommand extends Command
{
    protected function configure(): void
    {
        $this->addArgument('bar', InputArgument::OPTIONAL, 'Example optional argument.', 'defaultvalue');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        trim($input->getArgument('bar'));

        return 0;
    }
}
```

**Comment by seferov** [comment]
@jaikdean thanks for reporting. https://github.com/psalm/psalm-plugin-symfony/pull/87 should fix it
