### ISSUE TITLE
Using service locators with private services results in false-positives

### ISSUE THREAD

**Issue by jaikdean** [psalm/psalm-plugin-symfony#82]
We have a couple of classes implementing `Symfony\Contracts\Service\ServiceSubscriberInterface` to allow autowiring of service locators in problems areas where there are issues with circular references. This plugin currently reports `ERROR: PrivateService - … - Private service "Foo\Bar" used in container::get()` in these scenarios.

Is there a way to annotate our services accordingly, as I understand parsing the return value of `::getSubscribedServices()` would be impossible in many scenarios.

**Comment by seferov** [comment]
Thanks for the report.
It should be fixed with https://github.com/psalm/psalm-plugin-symfony/pull/101. If it doesn't covers all scenarios please let me know.
