### ISSUE TITLE
Notice after update psalm to 3.17.1

### ISSUE THREAD

**Issue by bondarenko-vadym** [psalm/psalm-plugin-symfony#93]
PHP Notice:  Undefined property: Psalm\Codebase::$taint in /home/vadim/projects/the-real-estate-tours/vendor/psalm/plugin-symfony/src/Twig/AnalyzedTemplatesTainter.php on line 27

**Comment by seferov** [comment]
@bondarenko-vadym thank you for the report. It is fixed.
